server:
  servlet:
    context-path: /baseproject
  port: 2405

spring:
# 集群
#  redis:
#    database: 0
#    host: 204.13.155.52:6379,204.13.155.52:6377
#    password: mapple  # 密码（默认为空）
#    timeout: 6000  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: 6000      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接

  redis:
    port: 6379
    lettuce:
      pool:
        max-active: 500
        max-wait: 500
        max-idle: 500
        min-idle: 0
    timeout: 6000
    host: 204.13.155.52
    password: mapple
  # 缓存
  cache:
    redis:
      time-to-live: 20s

  #druid
  datasource:
    name: test
    url: jdbc:mysql://204.13.155.52:3306/baseproject?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mapple
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20